variables:
  REPO_NAME: gita-healthcheck-generator
  VERSION: ${CI_COMMIT_TAG}
  PACKAGE_NAME: ${REPO_NAME}
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}/${VERSION}"

.platforms:
  PLATFORMS:
    - GOOS: linux
      GOARCH: amd64
    - GOOS: linux
      GOARCH: arm64
    - GOOS: windows
      GOARCH: amd64
    - GOOS: darwin
      GOARCH: amd64
    - GOOS: darwin
      GOARCH: arm64

stages:
  - build
  - upload
  - release

build:
  stage: build
  image: golang:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      mkdir -p dist
      for platform in $(echo "$PLATFORMS" | jq -c '.[]'); do
        export GOOS=$(echo $platform | jq -r '.GOOS')
        export GOARCH=$(echo $platform | jq -r '.GOARCH')
        
        # Set binary name based on platform
        if [ "$GOOS" = "windows" ]; then
          binary_name="${REPO_NAME}-${VERSION}-${GOOS}-${GOARCH}.exe"
        else
          binary_name="${REPO_NAME}-${VERSION}-${GOOS}-${GOARCH}"
        fi
        
        echo "Building for $GOOS/$GOARCH..."
        CGO_ENABLED=0 go build -o "dist/${binary_name}" -ldflags="-X 'main.Version=${VERSION}'" ./main.go
        
        # Create checksum
        cd dist && sha256sum "${binary_name}" > "${binary_name}.sha256" && cd ..
      done
  artifacts:
    paths:
      - dist/

upload:
  stage: upload
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - build
  script:
    - |
      for file in dist/*; do
        filename=$(basename $file)
        echo "Uploading $filename to Package Registry..."
        curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
          --upload-file $file \
          "${PACKAGE_REGISTRY_URL}/${filename}"
      done

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - upload
  script:
    - |
      # Prepare assets links for all files
      assets_links=""
      for file in dist/*; do
        filename=$(basename $file)
        assets_links="$assets_links --assets-link={\"name\":\"$filename\",\"url\":\"${PACKAGE_REGISTRY_URL}/${filename}\"}"
      done
      
      # Create release with all assets
      release-cli create \
        --name "Release ${VERSION}" \
        --tag-name $CI_COMMIT_TAG \
        --description "Release ${VERSION}" \
        $assets_links